## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [21]:
def compute(a,b):
    try:
        return a/b
    except(ZeroDivisionError):
        return "Cannot divide by zero"

print(compute(5,0))

Cannot divide by zero


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [7]:
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["Baseball","Cricket"]
for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(sub + " " + verb +' '+ obj + '.')

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [18]:
import numpy as np

def matrix(x,N=None):
    x = np.asarray(x)
    if x.ndim != 1:
        raise ValueError("x must be a one-dimensional array or sequence.")
    if N is None:
        N = len(x)

    v = np.empty((len(x), N), dtype=np.promote_types(x.dtype, int))
    tmp = v

    if N > 0:
        tmp[:, 0] = 1
    if N > 1:
        tmp[:, 1:] = x[:, None]
        np.multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

    return v

print(matrix([1,2,3,4,5]))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
